name: BUUUG
description: This file help you do to a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir correctement tous les champs
  - type: dropdown
    id: enviro
    attributes:
      label: Environnement
      description: Sur quel environnement ?
      options:
        - local
        - pre-prod
        - prod
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Que s"\u0027"est-il passé ? 
      placeholder: Quel est le bug ? 
    validations:
      required: true
  - type: textarea
    id: reproduire
    attributes:
      label: Comment reproduire le bug ? 
      description: Quel est le parcours, l"\u0027"utilisateur ? 
      placeholder: Jonh DOE 
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Quels sont les log"\u0027"s (debug)
      description: Log de la console ou du debugger
      render: shell
- type: textarea
    id: tester
    attributes:
      label: Le bug est résolu ! Que faire pour tester ? 
      description: Les étapes pour tester ?
 
