name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir correctement tous les champs!
  - type: dropdown
    id: enviro
    attributes:
      label: Environnement
      description: Sur quel environnement ?
      options:
        - local
        - pre-prod
        - prod
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Que s'est-il passé ? 
      placeholder: Le bug est...
    validations:
      required: true
  - type: textarea
    id: reproduire
    attributes:
      label: Comment reproduire le bug ? 
      description: Quel est le parcours, l'utilisateur ? 
      placeholder: Pour reproduire le bug il faut...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Quel est le navigateur utilisé ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Quels sont les logs (debug)
      description: Log de la console ou du debugger
      render: shell
  - type: textarea
    id: test
    attributes:
      label: Le bug est résolu ! Que faire pour tester ? 
      description: Les étapes pour tester ?
      placeholder: Pour tester il faut...
  - type: textarea
    id: impact
    attributes:
      label: Quels sont les élèments impactés ?
      description: Quels sont les élèments impactés ? 
      placeholder: Formulaires, state, commandes...

